
-- STEP 1: CREATE THE DATABASE
-- A database is like a big cupboard.
-- We keep all the tables and procedures for this project inside it.

CREATE OR REPLACE DATABASE project_1;

-- USE means: "Snowflake, work inside this database now."

USE DATABASE project_1;


-- STEP 2: CREATE THE SCHEMA
-- A schema is like a smaller cupboard inside the database.
-- It keeps related objects together.

CREATE OR REPLACE SCHEMA billing_software;

-- Tell Snowflake to use this schema for our objects.

USE SCHEMA billing_software;


-- STEP 3: CREATE THE ITEM_MASTER TABLE
-- A table is like an Excel sheet with rows and columns.
-- This table stores the items available in our shop.

CREATE OR REPLACE TABLE item_master
(
    -- The unique code used to identify an item.
    -- VARCHAR means this column stores text.

    item_code VARCHAR,

    -- The actual name of the item.

    item_name VARCHAR,

    -- How many units of the item are available in stock.
    -- NUMBER stores numeric values.

    item_qty NUMBER,

    -- The price of one unit of the item.

    item_rate NUMBER
);


-- STEP 4: CREATE THE CASH_MASTER TABLE
-- This table stores the bills created for customers.
-- Every successful purchase will add a new row here.

CREATE OR REPLACE TABLE cash_master
(
    -- Stores the bill number generated by the sequence.

    bill_no NUMBER,

    -- Stores the date on which the bill is generated.

    bill_dt DATE,

    -- Stores the total amount the customer must pay.

    bill_amount NUMBER
);


-- STEP 5: CREATE A SEQUENCE OBJECT
-- A sequence automatically generates numbers.
-- We do not have to type bill numbers manually.
--
-- START = 1 means the first generated number is 1.
-- INCREMENT = 1 means the next number increases by 1.
--
-- Example:
-- First bill  = 1
-- Second bill = 2
-- Third bill  = 3
--
-- NEXTVAL asks the sequence for its next number.

CREATE OR REPLACE SEQUENCE bill_no_seq
    START = 1
    INCREMENT = 1;


-- STEP 6: INSERT ITEMS INTO ITEM_MASTER
-- INSERT INTO means we want to add new rows to a table.
-- Each group of values represents one item.

INSERT INTO item_master VALUES
('IT001', 'Hamam', 100, 35),
('IT002', 'Harpic', 60, 501),
('IT003', 'Horlicks', 90, 88),
('IT004', 'Pears', 54, 76);


-- STEP 7: CHECK THE DATA
-- SELECT * means show every column.
-- FROM tells Snowflake which table to read.

SELECT * FROM item_master;

-- No bills have been generated yet, so this table
-- will initially have no rows.

SELECT * FROM cash_master;


-- STEP 8: CREATE THE STORED PROCEDURE
-- A stored procedure is a set of instructions saved in Snowflake.
-- We can run all those instructions by calling the procedure.
--
-- CREATE OR REPLACE means create it if necessary,
-- or replace the existing procedure with this version.
--
-- prc_item_master is the name of our procedure.
--
-- p_item_code is the item code supplied by the customer.
-- Example: 'IT001'
--
-- p_item_qty is the quantity the customer wants to buy.
-- Example: 32
--
-- RETURNS VARCHAR means the procedure returns a text message.
--
-- LANGUAGE SQL means we are writing the procedure using SQL.
--
-- AS $$ and $$ mark the beginning and end of the procedure body.

CREATE OR REPLACE PROCEDURE prc_item_master
(
    p_item_code VARCHAR,
    p_item_qty NUMBER
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$

-- STEP 9: DECLARE VARIABLES
-- A variable is a small temporary storage box.
-- We put a value into it and use that value later.
--
-- DECLARE is where we tell Snowflake which variables we need.

DECLARE

    -- This variable stores the number of matching item records.
    -- We use it to check whether the item code exists.

    lv_count NUMBER;

    -- This variable stores the available quantity of the item.

    lv_qty NUMBER;

    -- This variable stores the price of one unit.

    lv_rate NUMBER;

    -- This variable stores the calculated total bill amount.

    lv_bill_amt NUMBER;

BEGIN

    -- STEP 10: CHECK WHETHER THE ITEM EXISTS
    --
    -- SELECT COUNT(*) counts how many rows match our condition.
    -- WHERE item_code = p_item_code searches for the requested code.
    --
    -- INTO :lv_count puts the result into the variable lv_count.
    -- The colon is used to refer to a scripting variable in SQL.
    --
    -- If IT001 exists once, lv_count becomes 1.
    -- If IT999 does not exist, lv_count becomes 0.
    --
    -- This check is safer than trying to fetch a nonexistent
    -- item directly using SELECT ... INTO.

    SELECT COUNT(*)
    INTO :lv_count
    FROM item_master
    WHERE item_code = :p_item_code;


    -- STEP 11: STOP IF THE ITEM DOES NOT EXIST
    --
    -- IF checks whether a condition is true.
    -- Here we check whether lv_count is equal to zero.
    --
    -- RETURN sends a message back to the person calling
    -- the procedure and immediately stops its execution.
    --
    -- Because we stop here, no stock is changed and
    -- no bill is inserted when the item code is invalid.

    IF (lv_count = 0) THEN
        RETURN 'ITEM CODE IS NOT AVAILABLE';
    END IF;


    -- STEP 12: FETCH THE STOCK QUANTITY AND ITEM RATE
    --
    -- We already know the item exists.
    -- Now we fetch two values from the same matching row.
    --
    -- item_qty goes into lv_qty.
    -- item_rate goes into lv_rate.
    --
    -- SELECT ... INTO is an implicit-cursor-style approach:
    -- we retrieve the result directly into variables.
    -- We do not declare or open a cursor ourselves.

    SELECT item_qty, item_rate
    INTO :lv_qty, :lv_rate
    FROM item_master
    WHERE item_code = :p_item_code;


    -- STEP 13: CHECK WHETHER ENOUGH STOCK IS AVAILABLE
    --
    -- Compare the stock available with the requested quantity.
    --
    -- Example:
    -- lv_qty = 20
    -- p_item_qty = 30
    --
    -- 20 < 30 is TRUE.
    -- There are only 20 units, but the customer wants 30.
    -- Therefore, return an error message and stop.
    --
    -- No stock update or bill insertion happens after this RETURN.

    IF (lv_qty < p_item_qty) THEN
        RETURN 'AVAILABILITY IS LESSER THAN REQUIRED QTY. PLEASE CHANGE THE INPUT AND PROCEED';
    END IF;


    -- STEP 14: CHECK THAT THE QUANTITY IS POSITIVE
    --
    -- A customer should not purchase zero or negative units.
    -- This prevents an invalid quantity from being processed.
    --
    -- <= means "less than or equal to".

    IF (p_item_qty <= 0) THEN
        RETURN 'QUANTITY MUST BE GREATER THAN ZERO';
    END IF;


    -- STEP 15: CALCULATE THE BILL AMOUNT
    --
    -- Bill amount = rate of one item multiplied by quantity.
    --
    -- For example:
    -- lv_rate = 35 rupees
    -- p_item_qty = 32 units
    --
    -- 35 * 32 = 1120
    --
    -- The answer is stored in lv_bill_amt.

    lv_bill_amt := lv_rate * p_item_qty;


    -- STEP 16: REDUCE THE AVAILABLE STOCK
    --
    -- UPDATE changes an existing row in a table.
    --
    -- SET tells Snowflake which value should change.
    -- item_qty - p_item_qty subtracts the purchased quantity.
    --
    -- WHERE makes sure we update only the requested item.
    --
    -- Example:
    -- Previous stock = 100
    -- Purchased      = 32
    -- Remaining      = 68

    UPDATE item_master
    SET item_qty = item_qty - :p_item_qty
    WHERE item_code = :p_item_code;


    -- STEP 17: INSERT THE BILL INTO CASH_MASTER
    --
    -- INSERT INTO adds a new row to the cash_master table.
    --
    -- bill_no_seq.NEXTVAL asks the sequence for its next number.
    -- We do not manually enter 1, 2 or 3.
    --
    -- CURRENT_DATE() returns today's date.
    --
    -- lv_bill_amt contains the total amount calculated earlier.
    --
    -- Every successful call requests a new sequence number.
    -- The sequence is independent of the item quantity.

    INSERT INTO cash_master
    (
        bill_no,
        bill_dt,
        bill_amount
    )
    VALUES
    (
        bill_no_seq.NEXTVAL,
        CURRENT_DATE(),
        :lv_bill_amt
    );


    -- STEP 18: RETURN A SUCCESS MESSAGE
    --
    -- We reach this line only after the bill has been inserted.
    -- RETURN sends the success message to the caller.

    RETURN 'BILL GENERATED SUCCESSFULLY';

-- END marks the end of the procedure's instructions.

END;
$$;


-- STEP 19: CALL THE PROCEDURE
-- CALL means execute the stored procedure.
--
-- 'IT001' is the item code.
-- 32 is the quantity the customer wants to purchase.
--
-- The procedure checks stock, calculates the amount,
-- reduces stock and creates a bill.

CALL prc_item_master('IT001', 32);


-- STEP 20: CHECK THE UPDATED ITEM_MASTER TABLE
-- IT001 originally had 100 units.
-- After purchasing 32 units, it should have 68 units.
--
-- Other item quantities should remain unchanged.

SELECT * FROM item_master;


-- STEP 21: CHECK THE GENERATED BILL
-- A new row should appear in cash_master.
-- For this example, the bill amount should be 1120.
-- The bill number comes from bill_no_seq.

SELECT * FROM cash_master;


-- STEP 22: CALL THE PROCEDURE AGAIN
-- This is an optional second test.
-- The customer purchases 2 units of Harpic.
--
-- The amount is 2 * 501 = 1002.
-- The sequence supplies the next bill number.

CALL prc_item_master('IT002', 2);


-- STEP 23: VIEW ALL GENERATED BILLS
-- You should now see two successful bills.
-- Their bill numbers should be different.

SELECT * FROM cash_master;

-- STEP 24: VIEW THE UPDATED STOCK AGAIN

SELECT * FROM item_master;